# Generated by Django 3.2 on 2022-05-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_adminuser_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='mobile_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
