# Generated by Django 3.2 on 2022-05-18 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_auto_20220509_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name_plural': 'AdminUser'},
        ),
    ]
