# Generated by Django 3.1.13 on 2022-05-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_auto_20220518_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='is_superuser',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
