# Generated by Django 3.1.13 on 2022-05-20 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_datetime', models.DateField(auto_now_add=True)),
                ('clocking_time', models.DateTimeField()),
                ('logging', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=3)),
                ('ip_address', models.GenericIPAddressField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('clock_in_time', models.TimeField(blank=True, null=True)),
                ('clock_out_time', models.TimeField(blank=True, null=True)),
                ('status', models.BooleanField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_timesheet_employee', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_timesheet_recorded_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'clocking_time',
            },
        ),
    ]
